### PR TITLE
Making Venus available in Lu

### PR DESCRIPTION
**Pull request by smfoote**
I force-committed the .venus directory, because we need to customize the Lu-specific template in .venus/templates/lu.tl

I modified a few of the current tests to work with Venus as a part of my testing.

### CODE REVIEW

**Comment by Iheartweb** [comment]
@neborn Check this out and sync with @smfoote to see what else needs to be done.

**Comment by Iheartweb** [comment]
Before this is merged some fixes have to be in venus. ask @smfoote

Also please add the appropriate files to the gitignore.

**Comment by smfoote** [comment]
@Iheartweb All Venus dependencies are checked in.

**Comment by smfoote** [comment]
@neborn Please be concrete. A lot of work went into this pull request, and I would hate to lose it because of your impression of Venus's requirements. This _does_ work.

**Comment by neborn** [comment]
@smfoote and @sethmcl, I apologize for the abruptness and incompleteness of my previous comment. I will get in contact with you directly.

**Pull request closed without merging**
