### PR TITLE
List fixes for Accordion and better Deferred implementation for contain method

### PR DESCRIPTION
**Pull request by Jimgskoop**
Note I'm making this pull request from a branch on my repo.  Not sure if that's standard practice or not...?

### CODE REVIEW

**Comment by Iheartweb** [comment]
New version of inject?

**Comment by Jimgskoop** [comment]
Yes, I updated Inject because the debugging was broken in the previous version.

**Comment by Jimgskoop** [comment]
Sigh.  https://github.com/linkedin/inject/issues/136

**Comment by Iheartweb** [comment]
per your note above: That's a good way to do it.

**Pull request merged**
